import type { Category } from "@/types";

// 默认分类字典（与 tech-architecture.md 一致）
export const CATEGORIES: Category[] = [
  {
    key: "food",
    label: "餐饮",
    emoji: "🍜",
    color: "#B5651D",
    keywords: [
      "早餐",
      "早饭",
      "午餐",
      "午饭",
      "晚餐",
      "晚饭",
      "夜宵",
      "饭",
      "面",
      "粉",
      "外卖",
      "零食",
      "奶茶",
      "咖啡",
      "饮料",
      "水果",
      "菜",
      "吃",
      "餐",
      "食堂",
      "烧烤",
      "火锅",
      "汉堡",
      "寿司",
      "甜品",
    ],
  },
  {
    key: "transport",
    label: "交通",
    emoji: "🚇",
    color: "#6B8E6B",
    keywords: [
      "打车",
      "出租",
      "滴滴",
      "地铁",
      "公交",
      "巴士",
      "加油",
      "油费",
      "停车",
      "过路费",
      "高铁",
      "火车",
      "机票",
      "机票",
      "动车",
      "骑行",
      "共享单车",
      "车",
      "票",
    ],
  },
  {
    key: "shopping",
    label: "购物",
    emoji: "🛍️",
    color: "#C77B58",
    keywords: [
      "买",
      "购物",
      "衣服",
      "裤子",
      "鞋",
      "数码",
      "日用品",
      "超市",
      "电商",
      "下单",
      "充值",
      "书",
      "文具",
    ],
  },
  {
    key: "entertainment",
    label: "娱乐",
    emoji: "🎬",
    color: "#8B6F9E",
    keywords: [
      "电影",
      "游戏",
      "演出",
      "会员",
      "KTV",
      "演唱会",
      "剧本杀",
      "密室",
      "音乐",
      "视频",
    ],
  },
  {
    key: "home",
    label: "居家",
    emoji: "🏠",
    color: "#7A8B99",
    keywords: [
      "房租",
      "水电",
      "水费",
      "电费",
      "燃气",
      "物业",
      "宽带",
      "网费",
      "日用",
      "家居",
    ],
  },
  {
    key: "health",
    label: "健康",
    emoji: "💊",
    color: "#A0522D",
    keywords: ["药", "医院", "挂号", "体检", "看病", "诊所", "健身", "运动"],
  },
  {
    key: "other",
    label: "其他",
    emoji: "📌",
    color: "#9A9088",
    keywords: [],
  },
];

const CATEGORY_MAP: Record<string, Category> = CATEGORIES.reduce(
  (acc, c) => {
    acc[c.key] = c;
    return acc;
  },
  {} as Record<string, Category>,
);

export function getCategory(key: string): Category {
  return CATEGORY_MAP[key] ?? CATEGORY_MAP.other;
}
